[package]
name = "grammar"
version = "0.0.5"
authors = ["Pastor <viruszold@gmail.com>"]
description = "Lam"
homepage = "https://but.ru"
repository = "https://github.com/Pastor/BuT"
readme = "../README.md"
keywords = ["Lam", "framework", "code", "generation"]
license = "BSD"
edition = "2024"
exclude = ["src/grammar.lalrpop"]
include = ["Cargo.toml", "src/**/*", "src/ast.rs", "README.md", "LICENSE*"]

[[bin]]
name = "lamc"
path = "src/bin/lamc.rs"

[[bin]]
name = "lam-lsp"
path = "src/bin/lam_lsp.rs"
required-features = ["lsp"]

[build-dependencies]
lalrpop = { git = "https://github.com/lalrpop/lalrpop.git", version = "^0.23.1", features = ["lexer"] }

[dependencies]
lalrpop-util = { git = "https://github.com/lalrpop/lalrpop.git", version = "^0.23.1" }
thiserror = "2.0.18"
phf = { version = "0.13.1", features = ["macros"] }
unicode-xid = "0.2"
itertools = "0.14.0"
serde = { version = "^1.0", features = ["derive"], optional = true }
log = "0.4.29"
serde_json = { version = "1", optional = true }
lsp-server = { version = "0.7", optional = true }
lsp-types = { version = "0.97", optional = true }
svg = "0.18.0"
petgraph = "0.8.3"
rand = "0.10.1"
rand_distr = "0.6.0"

[dev-dependencies]
serde_json = "1.0.149"
tempfile = "3"

[features]
default = []
ast-serde = ["serde"]
lsp = ["dep:serde_json", "dep:lsp-server", "dep:lsp-types"]
