name = "BuT"
grammar = "but"
path_suffixes = ["but"]
line_comments = ["// ", "/// "]
autoclose_before = ";:.,=}])"
tab_size = 4
hard_tabs = false

language_servers = ["but-lsp"]

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]

[overrides.identifier]
word_characters = ["_"]
